# https://github.com/awesome-containers/static-bash
ARG STATIC_BASH_VERSION=5.2.15
ARG STATIC_BASH_IMAGE=ghcr.io/awesome-containers/static-bash

# https://github.com/awesome-containers/static-procps
ARG STATIC_PROCPS_VERSION=3.8
ARG STATIC_PROCPS_IMAGE=ghcr.io/awesome-containers/static-procps

# https://github.com/awesome-containers/alpine-build-essential
ARG BUILD_ESSENTIAL_VERSION=3.17
ARG BUILD_ESSENTIAL_IMAGE=ghcr.io/awesome-containers/alpine-build-essential


FROM $STATIC_BASH_IMAGE:$STATIC_BASH_VERSION-slim AS static-bash
FROM $STATIC_PROCPS_IMAGE:$STATIC_PROCPS_VERSION AS static-procps
FROM $BUILD_ESSENTIAL_IMAGE:$BUILD_ESSENTIAL_VERSION AS build

WORKDIR /src/procps
COPY --from=static-procps /bin/ ./

RUN set -xeu; \
    rm -f bash; \
    upx --no-progress --no-color ./*; \
    upx -t --no-progress --no-color ./*; \
    chmod -cR 755 ./; \
    chown -cR 0:0 ./; \
    ./sysctl --version

# slim static procps image
FROM static-bash
COPY --from=build /src/procps/ /bin/
